#!/bin/sh
# pets: destfile=/home/ema/bin/update-i3status, owner=ema, group=ema, mode=0755
# pets: package=i3status

cat << EOF
general {
        colors = true
        interval = 5
}

order += "wireless _first_"
order += "battery 0"
order += "read_file tstate"

EOF

for i in `seq 0 1`; do
    echo "order += \"cpu_temperature $i\""
done

cat << EOF

order += "tztime local"

wireless _first_ {
        format_up = "W: (%quality at %essid) %ip"
        format_down = "W: down"
}

battery 0 {
        format = "%status %percentage %remaining %consumption"
        format_down = "No battery"
        status_chr = "⚡ CHR"
        status_bat = "🔋 BAT"
        status_unk = "? UNK"
        status_full = "☻ FULL"
        path = "/sys/class/power_supply/qcom-battmgr-bat/uevent"
        low_threshold = 10
}

tztime local {
	format = "%Y-%m-%d %H:%M:%S"
}
EOF

num=0
for f in /sys/devices/virtual/thermal/thermal_zone*/hwmon*/name ; do
        if grep -q '^cpu[0,4]' $f; then
		printf "\ncpu_temperature $num {\n"
		echo '   format = "%degrees °C"'
		echo "   path = \"`dirname $f`/temp1_input\""
		echo '}'
                num=$((num+1))
        fi
done

for d in /sys/class/thermal/cooling_device*/type; do
	if grep -q cpufreq-cpu4 $d; then
		printf "\nread_file tstate {\n"
		echo "    path = \"`dirname $d`/cur_state\""
		echo "    format = \"%title: %content\""
		echo "}"
	fi
done
